### PR TITLE
Update azapi.py

### PR DESCRIPTION
**Pull request by thesw4rm**
This program extracts the actual lyrics while using the faster and easier to write BeautifulSoup. However, it is optimized for Python 3. Converting to Python 2 will be simple.

### CODE REVIEW

**Comment by ytpillai** [comment]
I realized this is a dead project, so if you do not wish to edit this file, may I post my own on my own repository?

**Comment by ManasN** [comment]
Go ahead, I'm waiting!

**Comment by BlackRam98** [comment]
Yeah man, it's a dead project but it's possible a restart in the future :)

2015-08-30 7:50 GMT+02:00 Manas N <notifications@github.com>:

**Comment by FrancescoGuarneri** [comment]
@ytpillai dead project BUT it's possible a restart. By the way, do you know python?

**Comment by thesw4rm** [comment]
I know Python pretty well and have used it all sorts of places including a web server. Thank you for your approval; unfortunately, I recently lost a portion of my work that I had. I'm going to start working on it again very soon.

**Comment by thesw4rm** [comment]
Wow, it's been a while since I looked back here. Well, I built a new version of it. You can see on https://github.com/ytpillai/AZLyricsExtractor. I'll try to find time to get more info from the site. Thanks for your approval again!

**Comment by FrancescoGuarneri** [comment]
Thanks for the work you've built. I have no more time for this.

2016-04-15 4:46 GMT+02:00 ytpillai notifications@github.com:

**Pull request merged**
